# posts-api/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/postsdb
      API_PREFIX: ""
      CORS_ORIGIN: "*"
      PORT: 3001

volumes:
  postgres_data:
